#pragma once

#define SYSCLK_PLL (100 * _1MHZ)  // 100Mhz
#define SYSCLK_RC25M (25 * _1MHZ) // 25Mhz
#define SYSCLK_SOURCE_RC25M (0U)
#define SYSCLK_SOURCE_PLL (1U)

#define SYSTEM_UARTCLKPWR_RC25M (0U)
#define SYSTEM_UARTCLKPWR_PLL (1U)
#define SYSTEM_UARTCLKPWR_RC25M_Msk (SYSTEM_UARTCLKPWR_RC25M << SYSTEM_UARTCLKPWR_CLKSRC_Pos)
#define SYSTEM_UARTCLKPWR_PLL_Msk (SYSTEM_UARTCLKPWR_PLL << SYSTEM_UARTCLKPWR_CLKSRC_Pos)