#pragma once

typedef enum
{
  EC_ERROR_OK = 0,
  EC_ERROR_SLOW_TIMER_OK = EC_ERROR_OK,
  EC_ERROR_SLOW_TIMER_INVALID_CHANNEL,
  EC_ERROR_SLOW_TIMER_POWER_OFF,
  EC_ERROR_I2C_OK = EC_ERROR_OK,
  EC_ERROR_I2C_INVALID_CHANNEL,
  EC_ERROR_I2C_INVALID_PARAMETER,
  EC_ERROR_UART_OK = EC_ERROR_OK,
  EC_ERROR_UART_INVALID_CHANNEL,
  EC_ERROR_UART_INVALID_PARAMETER,
  EC_ERROR_UART_POWER_OFF,
  EC_ERROR_UART_RX_EMPTY,
  EC_ERROR_UART_RECVBUF_FULL,
  EC_ERROR_ESPI_VW_OK = EC_ERROR_OK,
} EC_ERROR;

typedef EC_ERROR ec_error_t;